spring.application.name=gestion-taller

# Database

spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:C:/dev/mbs-gestion-taller/src/main/resources/tallerDB; AUTO-SERVER=true
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
